# Generated by Django 4.2.21 on 2025-05-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailverificationcode",
            old_name="code",
            new_name="confirmation_code",
        ),
    ]
